### ISSUE TITLE
Crashed Xorg on AMD GPUPro driver

### ISSUE THREAD

**Issue by cathalgarvey** [hughperkins/tensorflow-cl#13]
`python3 recurrent_network.py` crashes, dragging down Xorg with it.

I can't copy/paste the error from Ubuntu's bugchecker, for some reason (???), so I screenshotted the information, which included stack and traceback information. But, the basic error appears to land within the AMD GPU Pro driver code, with it trying to execute at 0x00... so perhaps a function pointer somewhere is being passed as null instead of pointing to an OpenCL function as intended?

Please enjoy a wall of images..

![cropped_error-0](https://cloud.githubusercontent.com/assets/1167837/20970651/7df6524a-bc86-11e6-8f2f-d5c50e8fde4e.png)
![cropped_error-1](https://cloud.githubusercontent.com/assets/1167837/20970653/7e357ad8-bc86-11e6-876c-95337ad5f2a7.png)
![cropped_error-2](https://cloud.githubusercontent.com/assets/1167837/20970655/7e3aca4c-bc86-11e6-8308-4c2547cd8808.png)
![cropped_error-3](https://cloud.githubusercontent.com/assets/1167837/20970656/7e3dbf86-bc86-11e6-968e-538aa12dfa3f.png)
![cropped_error-4](https://cloud.githubusercontent.com/assets/1167837/20970657/7e40771c-bc86-11e6-88f3-4b5de48ba8a8.png)
![cropped_error-5](https://cloud.githubusercontent.com/assets/1167837/20970654/7e3871e8-bc86-11e6-9e4f-c3cdf41fa103.png)
![cropped_error-6](https://cloud.githubusercontent.com/assets/1167837/20970652/7e1a6072-bc86-11e6-8c4b-eb9e75611fff.png)
![cropped_error-7](https://cloud.githubusercontent.com/assets/1167837/20970658/7e4bea16-bc86-11e6-923e-496f6e59e00d.png)
![cropped_error-8](https://cloud.githubusercontent.com/assets/1167837/20970659/7e581390-bc86-11e6-94f4-61fbdf45b0fb.png)
![cropped_error-9](https://cloud.githubusercontent.com/assets/1167837/20970660/7e5a7ad6-bc86-11e6-9d78-fda45bf69a44.png)
![cropped_error-10](https://cloud.githubusercontent.com/assets/1167837/20970661/7e630b06-bc86-11e6-828f-27f8ad866401.png)
![cropped_error-11](https://cloud.githubusercontent.com/assets/1167837/20970662/7e66f810-bc86-11e6-9682-93735fe533e8.png)
![cropped_error-12](https://cloud.githubusercontent.com/assets/1167837/20970663/7e6d48e6-bc86-11e6-86cd-057f6f767b10.png)
![cropped_error-13](https://cloud.githubusercontent.com/assets/1167837/20970664/7e7971d4-bc86-11e6-8019-540de2108b1c.png)
![cropped_error-14](https://cloud.githubusercontent.com/assets/1167837/20970665/7e844d16-bc86-11e6-98aa-52666e11efd5.png)
![cropped_error-15](https://cloud.githubusercontent.com/assets/1167837/20970666/7e88b338-bc86-11e6-8491-c7b14398478d.png)

**Comment by hughperkins** [comment]
Ok. Unfortunately I dont have the source-code to the AMD GPU driver :-P  In the absence of that we need to do bisection to localize the error. Or basically, find the simplest program that triggers the error basically.

Did you try the other tests? Do they all run? Is it only the recurrent_network that triggers the crash?  Have you run the python tests in https://github.com/hughperkins/cuda-on-cl to completion for example?

**Comment by hughperkins** [comment]
I made some updates to some of the event/driver/context code recently, so its *possible*, but far from certain, that that might have affected this bug in some way, ideally for the better.  Might be worth grabbing latest version and retrying. I should probably build a wheel to facilitate that. For ubuntu 16.04 is that right?

**Comment by hughperkins** [comment]
If you get a moment, do you mind building latest `tensorflow-cl` branch, and seeing if that helps at all?

**Comment by hughperkins** [comment]
(Also, can you confirm that latest https://github.com/hughperkins/coriander unit tests are/arent working?  There are three sets:
- `cd build; ./cocl_unittests`
- `cd build; make run-tests`
- `py.test -v`

I think you should run all of these, and report the results, please

)

**Comment by cathalgarvey** [comment]
I'll see what I can do! :) Very soon this error might be defunct anyway, as I may be moving from AMDGPU-pro to ROCm as the driver/OpenCL engine on my setup.

Unfortunately right now my system is in a woefully unstable situation due to experimenting with ROCm on partially supported hardware, but I have another boot drive that I can test this on.

**Comment by hughperkins** [comment]
Ah, no worries. Let's wait till you have the new stable system. No point in fixing bugs on a soon-to-be-obsolete system.

On 28 May 2017 14:13:50 BST, Cathal Garvey <notifications@github.com> wrote:
>I'll see what I can do! :) Very soon this error might be defunct
>anyway, as I may be moving from AMDGPU-pro to ROCm as the driver/OpenCL
>engine on my setup.
>
>Unfortunately right now my system is in a woefully unstable situation
>due to experimenting with ROCm on partially supported hardware, but I
>have another boot drive that I can test this on.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hughperkins/tensorflow-cl/issues/13#issuecomment-304513428

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hughperkins** [comment]
Lets close this for now then. We can reopen it if you have more recent results.

**Comment by hughperkins** [comment]
(Theres a new wheel out now, if you do have a moment to try, just for curiosity mostly I guess)
