### ISSUE TITLE
No env3

### ISSUE THREAD

**Issue by Whytehorse** [hughperkins/tensorflow-cl#15]
The install from source instructions say:
```
# build tensorflow
source ~/env3/bin/activate
```

But when running that I get:
`$ source ~/env3/bin/activate
bash: /home/ben/env3/bin/activate: No such file or directory`

And then all steps after that fail.

**Comment by yarrseni** [comment]
You have to create a virtual environment, for particular one yo've mentioned, it would be

`mkdir -p ~/env3/
cd ~/env3
virtualenv venv`

You could read more on Python virtual environments here: [py-docs/venv](http://docs.python-guide.org/en/latest/dev/virtualenvs/)

**Comment by Whytehorse** [comment]
OK, thank you. I didn't need to use a virtual environment. Perhaps the instructions could be updated to show that is optional and add the steps you mentioned.
