### ISSUE TITLE
Testing instructions

### ISSUE THREAD

**Issue by Whytehorse** [hughperkins/tensorflow-cl#18]
Is there a quick way to test my installation to ensure that tensorflow is using the GPU and OpenCL as desired?

**Comment by hughperkins** [comment]
Yes, if you do for example `with tf.device('/gpu:0'):`, then it forces everything under that to be on gpu0, or else crash.  You can also turn on device placement logging with `with tf.Session(config=tf.ConfigProto(log_device_placement=False)) as sess:`
