### ISSUE TITLE
unable to install .whl directly

### ISSUE THREAD

**Issue by guoyejun** [hughperkins/tensorflow-cl#20]
hi,

my system is ubuntu 16.04 64bit, i tried both pip and pi3, tried both to ln -s python to python2/python3 under /usr/bin

$ pip install --upgrade tensorflow-0.11.0rc0-py3-none-any.whl
tensorflow-0.11.0rc0-py3-none-any.whl is not a supported wheel on this platform.

i'm new to python, not sure if it is my env issue relative to python, do you happen to know to debug/fix it? thanks.

**Comment by guoyejun** [comment]
i must did something wrong that day.

i just tried again and it works now
![image](https://cloud.githubusercontent.com/assets/10448440/21758300/358a0854-d675-11e6-9039-1419f7b59efb.png)

**Comment by hughperkins** [comment]
Cool :-)
