### ISSUE TITLE
can't build from source

### ISSUE THREAD

**Issue by brazilla** [hughperkins/tensorflow-cl#25]
It seems bazel can't find gcc header for libraries like farmharsh,jpeg,png, yet these headers are indeed in search path of gcc.
This is an example for building the jpeg lib.
[](url)http://paste.ubuntu.com/24038831/

I'm using Ubuntu14.04.2 and gcc4.8.4.

**Comment by hughperkins** [comment]
Please upgrade to Ubuntu 16.04.  14.04 might work, but I wont directly support it.
