### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found

### ISSUE THREAD

**Issue by liyuankunbix** [hughperkins/tensorflow-cl#27]
the error comes from 
`  File "/home/bixian/.virtualenvs/tensorflow2/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)`
when i tried to `import tensorflow as tf` and it says 
`ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by /home/bixian/.virtualenvs/tensorflow2/lib/python3.4/site-packages/tensorflow/python/_pywrap_tensorflow.so)`

I tried 
`objdump -p _pywrap_tensorflow.so`
and it says 
`...blablabla...
Version References:
required from libm.so.6:
    0x09691a75 0x00 07 GLIBC_2.2.5
    0x06969183 0x00 05 GLIBC_2.23
...blablabla...`

I also tried 
`nm _pywrap_tensorflow.so|grep GLIBC_2.23`
and it says 
`U lgammaf@@GLIBC_2.23
                 U lgamma@@GLIBC_2.23`

Somehow, i believe this problem comes from my ubuntu which is Ubuntu 14.04.5 LTS with my custom Linux Kernel 3.16.36-031636-generic. Because when i tried `sudo apt-cache policy libc6`, it says `libc6:
  Installed: 2.19-0ubuntu6.9  Candidate: 2.19-0ubuntu6.9 ...blablabla`. 

Besides, I use python 3.4.3 in virtualenv environment as interpreter.

**Comment by hughperkins** [comment]
I support Ubuntu 16.04 lts.  Anything else will probably work, but I'm not going to actively support it.  If you can reproduce the issue on ubuntu 16.04, I might take a look. Note that python version on 16.04, out of the box, is 3.5, not 3.4.
