### ISSUE TITLE
multiple gpus not really working

### ISSUE THREAD

**Issue by hughperkins** [hughperkins/tensorflow-cl#29]
- cannot seem to use `CL_GPUOFFSET=1` to choose eg gpu 2
- nor does using `with tf.device('/gpu:1'):` seem to work

**Comment by hughperkins** [comment]
`CL_GPUOFFSET` works now.  Havent tested using `gpu:1` much yet

**Comment by hughperkins** [comment]
CL_GPUOFFSET is all I'm using for now.  Works ok :-) . Closing this for now.

**Comment by Michshelle** [comment]
Hello @hughperkins ,  

This issue persists on my side.  I'm using pre_compiled [tensorflow-cl](https://github.com/hughperkins/tf-coriander/releases/download/v0.18.3/tensorflow-cl-v0.18.3-macsierra-python3.zip).
Although I'm on macos mojave, it works most of the time only that switching GPU does not work...
