### ISSUE TITLE
undefined symbol: _ZN7clblast13CacheClearAllEv

### ISSUE THREAD

**Issue by inferrna** [hughperkins/tensorflow-cl#4]
Can't load python module:
```
/usr/local/lib/python3.5/dist-packages/tensorflow/python/../third_party/cuda-on-cl/libcocl.so: undefined symbol: _ZN7clblast13CacheClearAllEv
```
No any symbol similar to _ZN7clblast13CacheClearAllEv was found with
```
nm /usr/local/lib/python3.5/dist-packages/tensorflow/python/../third_party/cuda-on-cl/libclblast.so|grep -i cache|grep -i clear
```

**Comment by hughperkins** [comment]
```
nm build/clblast/libclblast.so | grep CacheClear
00000000000b0a80 T _ZN7clblast13CacheClearAllEv
```

Can you try maybe:
```
rm -Rf build/clblast
make -j 4
```
(from the `third_party/cuda-on-cl` directory)

(Once you've built it, you can just copy it across to the python folder, probably, dont need to rebild the entire tensorflow wheel, hopefully)

**Comment by hughperkins** [comment]
(oh, you might need to do `git pull` from the `cuda-on-cl` directory)

**Comment by hughperkins** [comment]
(it is here basicaly: https://github.com/hughperkins/CLBlast/blob/static-linking/src/cache.cpp#L112 )
