### ISSUE TITLE
Where is the cuda (.cu) files?

### ISSUE THREAD

**Issue by alephman** [hughperkins/tensorflow-cl#5]
can I ask a stupid question: 
I don't see any .cu cuda files in tensorflow source code, how to use cocl to transform them into cl files?

**Comment by hughperkins** [comment]
- they have the suffix `.cu.cc`, otherwise bazel chokes
- they're in `tensorflow/core/kernels`

On the whole, I prefer first to try testing against Eigen, standalone, before trying in tensorflow.  Tensorflow bulid is kind of heavy...  There are some Eigen tests at https://bitbucket.org/hughperkins/eigen/src/e9caed055dff038f18fe6379a89098376d4a64eb/unsupported/test/cuda-on-cl/?at=eigen-cl

**Comment by alephman** [comment]
Hi hughperkins,
The steps I did like this:
1. download and compile the easycl
cd /home/linaro
git clone --recursive https://github.com/hughperkins/EasyCL.git
cd EasyCL
mkdir build
cd build
cmake ..
make install

2.  modify the files:

cocl-issue3-a.cpp file:
change-->
#include " EasyCL/EasyCL.h"
to -->
#include "easycl/EasyCL.h"

run.sh file:
#!/bin/bash

set -x
set -e

#COCL_HOME=/home/linaro/cuda-on-cl   # or wherever it is

mkdir -p build
clang++-3.8 -DUSE_CLEW -fPIC -I/home/linaro/EasyCL/dist/include -c -o build/cocl-issue3-a.o cocl-issue3-a.cpp -std=c++11
g++ -fPIC -pie -Wl,-rpath,/home/linaro/EasyCL/dist/lib -o build/cocl-issue3-a build/cocl-issue3-a.o -lEasyCL -lclew
build/cocl-issue3-a


3.  this result is good:

+ set -e
+ COCL_HOME=/home/linaro/cuda-on-cl
+ mkdir -p build
+ clang++-3.8 -DUSE_CLEW -fPIC -I/home/linaro/EasyCL/dist/include -c -o build/cocl-issue3-a.o cocl-issue3-a.cpp -std=c++11
+ g++ -fPIC -pie -Wl,-rpath,/home/linaro/EasyCL/dist/lib -o build/cocl-issue3-a build/cocl-issue3-a.o -lEasyCL -lclew
+ build/cocl-issue3-a
createForindexedgpu gpu=0 verbose=1
clpresent:1
checking platform id 0x558604bb90
clGetDeviceIDs:0gpu=0 currentGpuIndex=0 num_devices=1
Using Imagination Technologies , OpenCL platform: PowerVR Rogue
Using OpenCL device: PowerVR Rogue G6230
clfinish finished ok
a[0]=555
a[1]=555
a[2]=123
a[3]=555
a[4]=555
