### ISSUE TITLE
Building issue on x86

### ISSUE THREAD

**Issue by alephman** [hughperkins/tensorflow-cl#8]
Following your instruction: https://github.com/hughperkins/tensorflow-cl/blob/tensorflow-cl/doc/build-from-source.md
1) # install bazel
install bazel 0.4.0 by apt-get (bazel.io) 

2) # install cuda-on-cl
git clone   --recursive https://github.com/hughperkins/cuda-on-cl
git checkout runtime-compile
cd cuda-on-cl
mkdir build
cd build 
cmake ..
make -j8
sudo make install 

cd ../test/cocl
cocl -fPIC cuda-sample.cu
./cuda-sample     // make sure that cocl works.

2)git clone --recursive https://github.com/hughperkins/tensorflow-cl
./configure
# put python path: /usr/bin/python3
# 'no' for hadoop, gpu, cloud, etc
bazel run --verbose_failures --logging 6 //tensorflow/tools/pip_package:build_pip_package

ERROR: /Work1/OpenCL/tensorflow-cl/te
nsorflow/python/BUILD:1773:1: in cc_library rule //tensorflow/python:tf_session_helper: non-test target '//tensorflow/python:tf_session_helper' depends on testonly target '//tensorflow/python:construction_fails_op' and doesn't have testonly attribute set.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 0.240s
ERROR: Build failed. Not running target

**Comment by hughperkins** [comment]
Please use Basel 0.3.2

On 17 November 2016 13:21:26 GMT+00:00, alephman <notifications@github.com> wrote:
>Following your instruction:
>https://github.com/hughperkins/tensorflow-cl/blob/tensorflow-cl/doc/build-from-source.md
>1) # install bazel
>install bazel 0.4.0 by apt-get (bazel.io) 
>
>2) # install cuda-on-cl
>git clone   --recursive https://github.com/hughperkins/cuda-on-cl
>git checkout runtime-compile
>cd cuda-on-cl
>mkdir build
>cd build 
>cmake ..
>make -j8
>sudo make install 
>
>cd ../test/cocl
>cocl -fPIC cuda-sample.cu
>./cuda-sample     // make sure that cocl works.
>
>2)git clone --recursive https://github.com/hughperkins/tensorflow-cl
>./configure
># put python path: /usr/bin/python3
># 'no' for hadoop, gpu, cloud, etc
>bazel run --verbose_failures --logging 6
>//tensorflow/tools/pip_package:build_pip_package
>
>
>ERROR: /Work1/OpenCL/tensorflow-cl/te
>nsorflow/python/BUILD:1773:1: in cc_library rule
>//tensorflow/python:tf_session_helper: non-test target
>'//tensorflow/python:tf_session_helper' depends on testonly target
>'//tensorflow/python:construction_fails_op' and doesn't have testonly
>attribute set.
>ERROR: Analysis of target
>'//tensorflow/tools/pip_package:build_pip_package' failed; build
>aborted.
>INFO: Elapsed time: 0.240s
>ERROR: Build failed. Not running target
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hughperkins/tensorflow-cl/issues/8

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
