### ISSUE TITLE
"Please set CLANG_HOME"

### ISSUE THREAD

**Issue by inferrna** [hughperkins/tensorflow-cl#9]
**cocl** on branch origin/working-on-incremental-function-building
**tensorflow-cl** on branch tensorflow-cl
```
INFO: From Compiling tensorflow/core/kernels/gather_functor_gpu.cu.cc:

Please set CLANG_HOME
```
cocl built with `CLANG_HOME=/usr/lib/llvm-3.8` and installed into /usr/local/

**Comment by hughperkins** [comment]
Yes, I need to integrate the latest cuda-on-cl with tensorflow.  I havent done that yet.

**Comment by hughperkins** [comment]
This might be addressed in https://github.com/hughperkins/cuda-on-cl/commit/d6ef4ee6c105fa50efffcb88cc2c0309c21c774f ? Eg, now, after doing `sudo make install` from the cuda-on-cl build directory, I can do:
```
 ~$ mkdir /tmp/foo
 ~$ cd /tmp/foo
 /tmp/foo$ env | grep CLANG
 /tmp/foo$ cp ~/git/cuda-on-cl/test/cocl/cuda_sample.cu .
 /tmp/foo$ cocl cuda_sample.cu 
 /tmp/foo$ ./cuda_sample 
```
![compile_no_clang_home](https://cloud.githubusercontent.com/assets/123560/20632370/f0b8ce3a-b334-11e6-906c-cf82d0facde7.png)

In this latest version `cocl` wraps `cocl_wrapped`, and defines `CLANG_HOME`:
```
$ cat /usr/local/bin/cocl
export CLANG_HOME=/usr/lib/llvm-3.8_
/usr/local/bin/cocl_wrapped "$@"
```
(my clang_home is in a weird place, cos I moved it, just for fun :-P )

**Comment by hughperkins** [comment]
(Hmmm, still broken from tensorflow-cl though.  let me fix that, and then update you)

**Comment by hughperkins** [comment]
(works slightly better with https://github.com/hughperkins/tensorflow-cl/commit/ef92f337c904d98035d7ce3d847a4159a3ffdd04 , but still doesnt quite build yet, I think)

**Comment by hughperkins** [comment]
I think it builds to completon again now in: 9ae5906

**Comment by hughperkins** [comment]
I think this is fixed now, right?
